name: CI/CD Factorial

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: make all

      - name: List files (debug)
        run: ls -la

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: first-binary
          path: ./first  # Указываем путь к бинарному файлу

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build  # Ждёт завершения build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: first-binary

      - name: List files (debug)
        run: ls -la

      - name: Move binary to working directory
        run: chmod +x first

      - name: Run tests
        run: |
          chmod +x tests/test.sh  # Делаем тесты исполнимыми
          ./tests/test.sh  # Запуск тестов

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: test  # Ждёт завершения тестов

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for packaging
        run: sudo apt-get update && sudo apt-get install -y build-essential dpkg-dev

      - name: Build .deb package
        run: make deb

      - name: List files (debug)
        run: ls -la

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: factorial-deb-package
          path: ./factorial_1.0-1_amd64.deb  # Убедитесь, что файл существует

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: package  # Ждёт завершения packaging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download .deb package
        uses: actions/download-artifact@v4
        with:
          name: factorial-deb-package
          path: buid

      - name: List files (debug)
        run: ls -la build

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          
      - name: Build Docker Image
        run: docker build -t factorial-app
      	
      - name: Run Docker container
        run: docker run --rm factorial-app
