name: CI/CD for Factorial App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: make all

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: factorial-binary
          path: factorial

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build  # Ждёт завершения build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: factorial-binary

      - name: Run tests
        run: |
          chmod +x tests/test.sh
          ./tests/test.sh

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: test  # Ждёт завершения test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: factorial-binary

      - name: Install packaging tools
        run: sudo apt-get install -y dpkg-dev debhelper

      - name: Build .deb package
        run: make deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: factorial-package
          path: factorial_1.0-1_amd64.deb

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: package  # Ждёт завершения package

    steps:
      - name: Download .deb package
        uses: actions/download-artifact@v4
        with:
          name: factorial-package

      - name: Deploy package
        run: |
          echo "Uploading package to repository..."
