name: CI/CD for Factorial App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential dpkg

      - name: Build the project
        run: make all

      - name: Run tests
        run: make test

      - name: Build .deb package
        run: make deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: factorial-deb
          path: package.deb
